--------------------------------------------------------------------
-- CLEANUP: Remove all Power User Skill Demo objects
--------------------------------------------------------------------

DROP DATABASE IF EXISTS POWER_USER_SKILL_DEMO;
DROP DBT PROJECT IF EXISTS POWER_USER_SKILL_DEMO.DBT_PROJECT.POWER_USER_SKILL_DEMO_DBT;
DROP DCM PROJECT IF EXISTS DATA_PRODUCT_CONTROL.PROJECTS.POWER_USER_SKILL_DEMO;
DROP STAGE IF EXISTS DATA_PRODUCT_CONTROL.PROJECTS.POWER_USER_SKILL_DEMO_STAGE;
