/*
==============================================================================
NPO Logging Demo: Setup Script
==============================================================================
Creates all infrastructure needed to demonstrate observability for
Notebook Project Objects (NPOs) in Snowflake.

Run this ONCE to set up the demo environment.
==============================================================================
*/

-- ============================================================
-- CONFIGURATION: Set these variables for your environment
-- ============================================================
SET demo_db        = 'NPO_LOGGING_DEMO';
SET demo_schema    = 'PIPELINE';
SET obs_schema     = 'OBSERVABILITY';
SET event_table    = 'NPO_LOGGING_DEMO.OBSERVABILITY.PIPELINE_EVENTS';
SET warehouse      = 'COMPUTE_WH';
SET compute_pool   = 'SYSTEM_COMPUTE_POOL_CPU';
SET runtime        = 'V2.2-CPU-PY3.11';
SET role           = 'ACCOUNTADMIN';

-- ============================================================
-- SETUP
-- ============================================================
USE ROLE IDENTIFIER($role);

-- Create Database and Schemas
CREATE OR REPLACE DATABASE IDENTIFIER($demo_db)
  COMMENT = 'Demo: NPO observability - print() vs logging module';

CREATE SCHEMA NPO_LOGGING_DEMO.PIPELINE
  COMMENT = 'ML pipeline notebook and NPO';

CREATE SCHEMA NPO_LOGGING_DEMO.OBSERVABILITY
  COMMENT = 'Event table for telemetry';

-- Create Event Table
CREATE EVENT TABLE IF NOT EXISTS IDENTIFIER($event_table)
  CHANGE_TRACKING = TRUE;

-- Associate Event Table
-- IMPORTANT: NPOs run as SPCS containers, which use the ACCOUNT-level event table.
-- If you ONLY set it at database level, NPO logs will NOT appear.
ALTER ACCOUNT SET EVENT_TABLE = $event_table;
ALTER DATABASE NPO_LOGGING_DEMO SET EVENT_TABLE = $event_table;

-- Set Telemetry Levels
-- CRITICAL: You need BOTH LOG_LEVEL and LOG_EVENT_LEVEL set.
--   LOG_LEVEL       = controls what log messages are generated by the runtime
--   LOG_EVENT_LEVEL = controls what gets WRITTEN to the event table
-- If you only set LOG_LEVEL, logs are generated but never persisted!
ALTER ACCOUNT SET LOG_LEVEL = 'INFO';
ALTER ACCOUNT SET LOG_EVENT_LEVEL = 'INFO';
ALTER ACCOUNT SET TRACE_LEVEL = 'ALWAYS';
ALTER ACCOUNT SET METRIC_LEVEL = 'ALL';

ALTER DATABASE NPO_LOGGING_DEMO SET LOG_LEVEL = 'INFO';
ALTER DATABASE NPO_LOGGING_DEMO SET LOG_EVENT_LEVEL = 'INFO';
ALTER DATABASE NPO_LOGGING_DEMO SET TRACE_LEVEL = 'ALWAYS';
ALTER DATABASE NPO_LOGGING_DEMO SET METRIC_LEVEL = 'ALL';

-- Create Stage for Notebook Files
CREATE OR REPLACE STAGE NPO_LOGGING_DEMO.PIPELINE.NOTEBOOK_FILES;

-- Upload Notebook (run from SnowSQL or Snowsight file upload)
-- PUT 'file:///path/to/npo_logging_demo.ipynb' @NPO_LOGGING_DEMO.PIPELINE.NOTEBOOK_FILES AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Create Notebook Project Object
CREATE NOTEBOOK PROJECT IF NOT EXISTS NPO_LOGGING_DEMO.PIPELINE.LOGGING_DEMO_PROJECT
  FROM '@NPO_LOGGING_DEMO.PIPELINE.NOTEBOOK_FILES'
  COMMENT = 'Demo: print() vs logging module observability in scheduled NPOs';

-- Create Task (far-future CRON so it never auto-runs; use EXECUTE TASK to trigger)
CREATE OR REPLACE TASK NPO_LOGGING_DEMO.PIPELINE.LOGGING_DEMO_TASK
  WAREHOUSE = $warehouse
  SCHEDULE = 'USING CRON 0 0 1 1 * America/Los_Angeles'
AS
  EXECUTE NOTEBOOK PROJECT "NPO_LOGGING_DEMO"."PIPELINE"."LOGGING_DEMO_PROJECT"
    MAIN_FILE = 'npo_logging_demo.ipynb'
    COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
    RUNTIME = 'V2.2-CPU-PY3.11'
    QUERY_WAREHOUSE = 'COMPUTE_WH';

ALTER TASK NPO_LOGGING_DEMO.PIPELINE.LOGGING_DEMO_TASK RESUME;

-- Verify Setup
SHOW PARAMETERS LIKE 'EVENT_TABLE' IN ACCOUNT;
SHOW PARAMETERS LIKE '%_LEVEL' IN ACCOUNT;
SHOW NOTEBOOK PROJECTS IN DATABASE NPO_LOGGING_DEMO;
SHOW TASKS IN DATABASE NPO_LOGGING_DEMO;
