-- ============================================================
-- 01: Database, Schemas, and Role Setup
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS MFG_SCHEDULING_REPORTING;

CREATE SCHEMA IF NOT EXISTS MFG_SCHEDULING_REPORTING.RAW;
CREATE SCHEMA IF NOT EXISTS MFG_SCHEDULING_REPORTING.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS MFG_SCHEDULING_REPORTING.ADMIN;

-- Roles
CREATE ROLE IF NOT EXISTS mfg_plant_manager;
CREATE ROLE IF NOT EXISTS mfg_scheduler;
CREATE ROLE IF NOT EXISTS mfg_platform_admin;

GRANT USAGE ON DATABASE MFG_SCHEDULING_REPORTING TO ROLE mfg_plant_manager;
GRANT USAGE ON DATABASE MFG_SCHEDULING_REPORTING TO ROLE mfg_scheduler;

GRANT USAGE ON SCHEMA MFG_SCHEDULING_REPORTING.RAW TO ROLE mfg_scheduler;
GRANT USAGE ON SCHEMA MFG_SCHEDULING_REPORTING.ANALYTICS TO ROLE mfg_plant_manager;
GRANT USAGE ON SCHEMA MFG_SCHEDULING_REPORTING.ANALYTICS TO ROLE mfg_scheduler;

GRANT SELECT ON ALL TABLES IN SCHEMA MFG_SCHEDULING_REPORTING.RAW TO ROLE mfg_scheduler;
GRANT SELECT ON ALL TABLES IN SCHEMA MFG_SCHEDULING_REPORTING.ANALYTICS TO ROLE mfg_plant_manager;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS MFG_REPORTING_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE MFG_REPORTING_WH TO ROLE mfg_plant_manager;
GRANT USAGE ON WAREHOUSE MFG_REPORTING_WH TO ROLE mfg_scheduler;

-- Stage for semantic view YAML
CREATE STAGE IF NOT EXISTS MFG_SCHEDULING_REPORTING.ANALYTICS.MODELS
    DIRECTORY = (ENABLE = TRUE);
