-- ============================================================
-- 06: Row Access Policy + Caller Grants (Demo 3)
-- ============================================================

USE DATABASE MFG_SCHEDULING_REPORTING;

-- Row access policy: each user sees only their assigned plants
CREATE OR REPLACE ROW ACCESS POLICY ADMIN.PLANT_ACCESS
AS (plant_id VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN')
    OR
    plant_id IN (
        SELECT plant_id
        FROM MFG_SCHEDULING_REPORTING.ADMIN.USER_PLANT_ASSIGNMENTS
        WHERE user_email = CURRENT_USER()
    );

-- Apply to relevant tables
ALTER TABLE RAW.DAILY_PRODUCTION_METRICS
    ADD ROW ACCESS POLICY ADMIN.PLANT_ACCESS ON (PLANT_ID);
ALTER TABLE RAW.WORK_ORDERS
    ADD ROW ACCESS POLICY ADMIN.PLANT_ACCESS ON (PLANT_ID);
ALTER TABLE RAW.ISSUES
    ADD ROW ACCESS POLICY ADMIN.PLANT_ACCESS ON (PLANT_ID);
ALTER TABLE RAW.DELIVERIES
    ADD ROW ACCESS POLICY ADMIN.PLANT_ACCESS ON (PLANT_ID);

-- Caller grants for Streamlit apps using caller's rights connection
-- The app-deployer role gets CALLER grants so the viewer's own access applies
GRANT MANAGE CALLER GRANTS ON ACCOUNT TO ROLE mfg_platform_admin;

GRANT CALLER USAGE ON DATABASE MFG_SCHEDULING_REPORTING TO ROLE mfg_platform_admin;
GRANT CALLER USAGE ON SCHEMA MFG_SCHEDULING_REPORTING.RAW TO ROLE mfg_platform_admin;
GRANT CALLER USAGE ON SCHEMA MFG_SCHEDULING_REPORTING.ANALYTICS TO ROLE mfg_platform_admin;
GRANT CALLER SELECT ON ALL TABLES IN SCHEMA MFG_SCHEDULING_REPORTING.RAW TO ROLE mfg_platform_admin;
GRANT CALLER SELECT ON ALL TABLES IN SCHEMA MFG_SCHEDULING_REPORTING.ANALYTICS TO ROLE mfg_platform_admin;
GRANT CALLER SELECT ON ALL VIEWS IN SCHEMA MFG_SCHEDULING_REPORTING.ANALYTICS TO ROLE mfg_platform_admin;
